### ISSUE TITLE
Github README

### ISSUE THREAD

**Issue by ibnunowshad** [MaryNfs/MaryNfs#1]
Maryam,

I am interested in https://github.com/MaryNfs/MaryNfs. I see that you forked it from https://github.com/Andrew6rant/Andrew6rant and get it done few days before. I am not core dev, but I can see his profile is failing to auto build due to node.js version mismatch. May I please ask your help to share the document, how did you get it fixed for your profile?

**Comment by MaryNfs** [comment]
Hi @ibnunowshad 
As you can see from [here](https://github.com/Andrew6rant/Andrew6rant/actions/runs/9917272942/job/27400555597), his repo is failing with a `502` error code and the message `Something went wrong while executing your query.` This may be the result of a timeout, or it could be a GitHub bug from the GitHub GraphQL API, indicating a potential timeout or rate limit issue.

Regarding the Node.js warning you mentioned, it's due to the use of deprecated GitHub Action packages (`actions/checkout@v2`,` actions/setup-python@v2`, `actions/cache@v2`). Thanks for pointing that out. I have fixed them in this [commit](https://github.com/MaryNfs/MaryNfs/commit/b9548aea2101092a51c580650c20765f9057b1dd).

**Comment by ibnunowshad** [comment]
For me now, the commit is failing with the [below errors](https://github.com/ibnunowshad/ibnunowshad/actions/runs/9925598583/job/27418426901). Any token permissions I should look at? I tried to check token permission already. However, I am unable to get it resolved.

```
Run git add .
  git add .
  git diff
  git config --global user.email "github-actions-bot@***.github.io"
  git config --global user.name "***/GitHub-Actions-Bot"
  git commit -m "Updated README" -a || echo "No changes to commit"
  git push
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
[main bddbb5c] Updated README
 2 files changed, 2 insertions(+), 2 deletions(-)
remote: Permission to ***/***.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/***/***/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```

**Comment by MaryNfs** [comment]
It seems you gh Actions bot doesn't have the necessary permissions to push changes to your repository. Go to your `repo Settings` -> `Action` -> `General` -> `Workflow permissions` and choose **read and write permissions**, I think by default it has read permission.

**Comment by ibnunowshad** [comment]
I guess, I sorted it. However, my `ACCESS_TOKEN` and `USERNAME` seems broken or unable to fetch something from `https://api.github.com/{username}`

Any specific `ACCESS_TOKEN` or `USERNAME` settings I have to look at?

**Comment by MaryNfs** [comment]
@ibnunowshad What is the error you are getting? It should fail [here](https://github.com/Andrew6rant/Andrew6rant/blob/d4dde43666a055c23493a716912af0d3ce04ff3e/today.py#L47) and raise an exception.

Update: As far as I can see, it is working for you, so closing the issue. Feel free to open another issue if you find something problematic.
